Repository only-arrow-function/Taskify, pull requests merged in 2024-04, with the labels that each got.

#4 [윤아영] 칩 컴포넌트 (완료: 다른 팀원 승인 대기)
  components/chips/color-chip.tsx
  components/chips/number-chip.tsx
  components/chips/progress-chip.tsx
  components/chips/tag-chip.tsx
  constants/chips.ts
  public/chips/check.svg
  types/color.ts
Labels: UI

#5 [이동현] PC 랜딩 헤더 (완료: 다른 팀원 승인 대기)
  .vscode/settings.json
  components/rending-header/rending-header-logo.tsx
  components/rending-header/rending-header-navbar.tsx
  components/rending-header/rending-header-type.ts
  components/rending-header/rending-header.tsx
  public/logo/logo-auth.svg
  public/logo/logo-large.svg
  public/logo/logo-small-darkmode.svg
  public/logo/logo-with-title-large-darkmode.svg
  public/logo/logo-with-title-large.svg
  tailwind.config.ts
Labels: UI

#10 [김재성] 사이드 바(완료: 다른 팀원 승인 대기)
  components/side-menu/side-menu-add-dash-boards.tsx
  components/side-menu/side-menu-dash-boards-list.tsx
  components/side-menu/side-menu-dash-boards.tsx
  components/side-menu/side-menu-logo.tsx
  components/side-menu/side-menu-type.ts
  components/side-menu/side-menu.tsx
  pages/test-side-menu.tsx
Labels: UI

#6 [노은수] : Feature/invite table (axios, swr 초기 셋팅이 포함되어 있으니, 빠르게 머지를 부탁드립니다.)
  .eslintrc.json
  apis/axios.ts
  apis/request.ts
  components/tables/invite-table.tsx
  hooks/swr/useDashboard.ts
  hooks/swr/useInviteUsers.ts
  hooks/swr/useUsers.ts
  package-lock.json
  package.json
  pages/temporary-eansu.tsx
Labels: UI

#9 [윤아영] 구성원 테이블 (완료: 다른 팀원 승인 대기)
  components/chips/color-chip.tsx
  components/chips/color-constants.ts
  components/chips/color-type.ts
  components/chips/progress-chip.tsx
  components/chips/tag-chip.tsx
  components/tables/members-table.tsx
  components/tables/members-type.ts
  components/tables/mock-members.ts
  components/tables/table-list-item.tsx
  pages/temporary-ayoung.tsx
  tailwind.config.ts
Labels: UI

#7 [구승모] Input 컴포넌트 ui 추가 (완료: 다른 팀원 승인 대기)
  components/inputs/input-field-type.ts
  components/inputs/input-field.tsx
  components/inputs/password-input.tsx
Labels: UI

#8 [이동현] dashboard UI (완료: 다른 팀원 승인 대기)
  .prettierrc.json
  components/dashboard/header/dashboard-header-button.tsx
  components/dashboard/header/dashboard-header-members.tsx
  components/dashboard/header/dashboard-header-profile.tsx
  components/dashboard/header/dashboard-header.tsx
  components/dashboard/invite/dashboard-invite-search.tsx
  components/dashboard/invite/dashboard-invite-table.tsx
  components/dashboard/invite/dashboard-invite.tsx
  components/dashboard/layout/dashboard-section-layout.tsx
  components/profile/profile-badge.tsx
  components/profile/profile-username.tsx
  components/rending-header/rending-header-logo.tsx
  components/rending-header/rending-header.tsx
  components/rending-header/rending-header.type.ts
  components/side-menu/side-menu.tsx
  pages/dashboard/index.tsx
  pages/my-dashboard/index.tsx
  public/dashboard/dashboard-invite.svg
  public/dashboard/dashboard-setting-icon.svg
  public/logo/logo-large.svg
  public/logo/logo-main.svg
  styles/globals.css
  tailwind.config.ts
Labels: UI

#12 [이동현] 초대받은 대시보드 컴포넌트 및 대시보드 페이지 (완료: 다른 팀원 승인 대기)
  .prettierrc.json
  components/dashboard/header/dashboard-header-button.tsx
  components/dashboard/header/dashboard-header-members.tsx
  components/dashboard/header/dashboard-header-profile.tsx
  components/dashboard/header/dashboard-header.tsx
  components/dashboard/invite/dashboard-invite-search.tsx
  components/dashboard/invite/dashboard-invite-table.tsx
  components/dashboard/invite/dashboard-invite.tsx
  components/dashboard/layout/dashboard-section-layout.tsx
  components/profile/profile-badge.tsx
  components/profile/profile-username.tsx
  components/rending-header/rending-header-logo.tsx
  components/rending-header/rending-header.tsx
  components/rending-header/rending-header.type.ts
  components/side-menu/side-menu.tsx
  pages/dashboard/index.tsx
  pages/my-dashboard/index.tsx
  public/dashboard/dashboard-invite.svg
  public/dashboard/dashboard-setting-icon.svg
  public/logo/logo-large.svg
  public/logo/logo-main.svg
  styles/globals.css
  tailwind.config.ts
Labels: UI

#15 [구승모] 로그인 페이지 추가
  apis/request.ts
  components/buttons/login-button.tsx
  components/inputs/input-field.tsx
  components/inputs/password-input.tsx
  hooks/useLogin.ts
  pages/login/index.tsx
Labels: Feature

#11 [윤아영] 모달 레이아웃 (완료: 다른 팀원 승인 대기)
  components/modal/backdrop.tsx
  components/modal/modal-button-group.tsx
  components/modal/modal-button.tsx
  components/modal/modal-layout.tsx
  components/modal/modal-new-todo.tsx
  components/modal/modal-newTodo-layout.tsx
  components/modal/modal-title.tsx
  components/modal/modal.tsx
Labels: UI

#19 [이동현] my-dashboard 페이지 UI (컴포넌트 결합 및 반응형)
  apis/request.ts
  components/buttons/domain/commons/dashboard-base.tsx
  components/buttons/domain/dashboard-open-button.tsx
  components/buttons/pagination/dashboard-pagination-button.tsx
  components/dashboard/list/dashboard-list.tsx
  components/dashboard/pagination/dashboard-pagination.tsx
  hooks/swr/dashboard/use-dashboards.ts
  pages/my-dashboard/index.tsx
  types/color.type.ts
Labels: UI

#24 [이동현] 대시보드 생성하기 (완료: 다른 팀원 승인 대기)
  .eslintrc.json
  apis/localStorage.ts
  apis/request.ts
  components/buttons/domain/commons/dashboard-base.tsx
  components/buttons/domain/dashboard-open-button.tsx
  components/buttons/domain/new-dashboard-add-button.tsx
  components/chips/color-chip-group.tsx
  components/chips/color-chip.tsx
  components/dashboard/dashboard.constants.ts
  components/dashboard/list/dashboard-list.tsx
  components/dashboard/modal/new-dashboard-modal.tsx
  components/inputs/input-field.tsx
  components/modal/backdrop.tsx
  components/modal/modal-button-group.tsx
  components/modal/modal-button.tsx
  components/modal/modal-layout.tsx
  hooks/swr/dashboard/use-dashboards.ts
  package-lock.json
  package.json
  store/index.ts
  store/modal/new-dashboard-slice.ts
  store/toggle-slice.ts
  tailwind.config.ts
Labels: UI, Feature

#25 [이동현] 마이 대시보드 페이지네이션 (완료: 다른 팀원 승인 대기)
  components/buttons/pagination/dashboard-pagination-button.tsx
  components/chips/color-chip-group.tsx
  components/dashboard/header/dashboard-header.tsx
  components/dashboard/list/dashboard-list-fetcher.tsx
  components/dashboard/list/dashboard-list.tsx
  components/dashboard/modal/new-dashboard-modal.tsx
  components/dashboard/pagination/dashboard-pagination.tsx
  components/modal/backdrop.tsx
  components/modal/modal-button-group.tsx
  hooks/swr/dashboard/use-dashboards.ts
  hooks/use-pagination.ts
  pages/my-dashboard/index.tsx
  store/dashboard/index.ts
  store/dashboard/new-dashboard-modal-slice.ts
  store/index.ts
  store/pagination-store.ts
  store/toggle-store.ts
Labels: Feature

#27 [이동현] 메인페이지완성 (완료: 다른 팀원 승인 대기)
  components/home/home-section-feature.tsx
  components/home/home-section-manual.tsx
  components/home/home-section-visual.tsx
  components/rending-footer/rending-footer.tsx
  components/rending-header/rending-header-logo.tsx
  components/rending-header/rending-header-navbar.tsx
  pages/index.tsx
  public/main/main-manual-1.svg
  public/main/main-manual-2.svg
  public/main/main-section-feature-1.svg
  public/main/main-section-feature-2.svg
  public/main/main-section-feature-3.svg
  public/main/main-visual.svg
Labels: UI

#26 [윤아영] table members
  apis/request.ts
  components/tables/members-table.tsx
  components/tables/members.type.ts
  components/tables/table-button.tsx
  components/tables/table-list-item.tsx
  hooks/swr/use-members.ts
Labels: Feature

#33 [이동현] 대시보드 페이지네이션 기능수정 (완료: 다른 팀원 승인 대기)
  apis/request.ts
  components/buttons/pagination/dashboard-pagination-button.tsx
  components/dashboard/list/dashboard-list-fetcher.tsx
  components/dashboard/list/dashboard-list-item-skeleton.tsx
  components/dashboard/list/dashboard-list-item.tsx
  components/dashboard/list/dashboard-list.tsx
  components/dashboard/pagination/dashboard-pagination-skeleton.tsx
  components/dashboard/pagination/dashboard-pagination.tsx
  hooks/swr/dashboard/use-dashboards.ts
  pages/my-dashboard/index.tsx
Labels: Feature

#34 [이동현] 모달 버그 수정 (완료: 다른 팀원 승인 대기)
  apis/request.ts
  components/dashboard/list/dashboard-list-item-skeleton.tsx
  components/dashboard/list/dashboard-list-item.tsx
  components/dashboard/list/dashboard-list.tsx
  components/dashboard/pagination/dashboard-pagination-skeleton.tsx
  components/dashboard/pagination/dashboard-pagination.tsx
  components/modal/modal-button-group.tsx
  components/side-menu/side-menu.tsx
  hooks/swr/dashboard/use-dashboards.ts
  pages/my-dashboard/index.tsx
Labels: bug

#36 [이동현] 로그인한 유저 정보 전역 상태관리 (완료: 다른 팀원 승인 대기)
  components/dashboard/header/dashboard-header-profile.tsx
  components/dashboard/header/dashboard-header.tsx
  pages/login/index.tsx
  pages/my-dashboard/index.tsx
  pages/signup/index.tsx
  store/auth.ts
Labels: Feature

#37 [윤아영] modal todo detail
  apis/cards-request.ts
  apis/comments-request.ts
  components/card/card-type.ts
  components/chips/tag-chip.tsx
  components/modal/info-with-label.tsx
  components/modal/modal-button.tsx
  components/modal/modal-edit-todo.tsx
  components/modal/modal-newTodo-layout.tsx
  components/modal/modal-todo-detail-layout.tsx
  components/modal/modal-todo-detail.tsx
  components/modal/todo/comment.tsx
  components/modal/todo/comment.type.ts
  components/modal/todo/popover.tsx
  components/modal/todo/profile-image.tsx
  components/modal/todo/textarea-with-label.tsx
  hooks/swr/use-card.ts
  hooks/use-comments.ts
  hooks/use-intersect.ts
  next.config.mjs
  pages/temporary-ayoung.tsx
  tailwind.config.ts
Labels: UI, Feature

#39 [이동현] 404페이지 (완료: 다른 팀원 승인 대기)
  components/buttons/basic-button.tsx
  pages/404.tsx
  pages/_app.tsx
Labels: UI

#40 [이동현] 로그인 후 마이 대시보드 페이지로 이동 [완료: 다른 팀원 승인 대기
  pages/login/index.tsx
Labels: bug

#38 마이페이지 추가 및 input 검증 수정
  apis/user-request.ts
  components/buttons/basic-button.tsx
  components/inputs/input-field.tsx
  components/inputs/password-input.tsx
  components/modal/notification-modal.tsx
  components/mypage/header/header.tsx
  components/mypage/management/management-skeleton.tsx
  components/mypage/management/management.tsx
  components/mypage/management/userinfo-type.ts
  components/mypage/password-change-form/password-change-form.tsx
  components/mypage/profile/profile.tsx
  hooks/swr/use-user.ts
  hooks/use-authentication-validation.ts
  pages/mypage/index.tsx
  pages/signup/index.tsx
  public/icon/profile-add.svg
Labels: Feature, Refactoring

#43 [이동현] 사이드바 메뉴 컬러 추가 및 스켈레톤
  auth/auth-hoc.tsx
  components/buttons/basic-button.tsx
  components/dashboard/layout/dashboard-layout.tsx
  components/dashboard/list/dashboard-list-item.tsx
  components/dashboard/modal/new-dashboard-modal.tsx
  components/inputs/input-field.tsx
  components/rending-header/rending-header-navbar.tsx
  components/rending-header/rending-header.tsx
  components/side-menu/side-menu-dash-boards-list.tsx
  components/side-menu/side-menu-dash-boards.tsx
  components/side-menu/side-menu-logo.tsx
  components/side-menu/side-menu-skeleton.tsx
  components/side-menu/side-menu-type.ts
  hooks/react-query/use-query-dashboard.ts
  hooks/react-query/use-query-invite-users.ts
  pages/_app.tsx
  pages/index.tsx
  pages/my-dashboard/index.tsx
  pages/mypage/index.tsx
Labels: UI, Feature

#49 [윤아영] comments 리액트 쿼리
  apis/comments-request.ts
  components/card/card-type.ts
  components/modal/modal-todo-detail.tsx
  components/modal/todo/comment.tsx
  components/modal/todo/comment.type.ts
  components/modal/todo/popover.tsx
  hooks/react-query/use-query-card.ts
  hooks/react-query/use-query-comments.ts
Labels: Feature
